name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/** ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Run tests
        working-directory: backend
        run: npm test